# Cargo.toml
[dependencies]
crossterm = "0.29.0"
rand = "0.9.1"
serde_json = "1.0.140"

[package]
name = "morseytype-cli"
version = "0.1.0"   
edition = "2021"

[profile.dev]
opt-level = 3
debug = false
